import type { LevelConfig } from './level-types'

export const LEVELS: LevelConfig[] = [
  {
    id: 'level1',
    name: 'Station Alpha',
    description: 'はじめての防衛ミッション。3 方向からの侵攻を防げ。',
    difficulty: 'easy',
    mapSize: 20,
    startGold: 300,
    startLives: 30,
    spawnPoints: [
      { x: 9, z: 9 },
      { x: -9, z: 9 },
      { x: 0, z: -9 },
    ],
    basePosition: { x: 0, z: 0 },
    obstacles: [],
    waves: [
      {
        enemyCount: 3,
        spawnInterval: 2.5,
        enemySpeed: 0.8,
        scorePerKill: 10,
        enemyHp: 2,
        goldPerKill: 10,
      },
      {
        enemyCount: 5,
        spawnInterval: 2.0,
        enemySpeed: 1.0,
        scorePerKill: 15,
        enemyHp: 3,
        goldPerKill: 15,
      },
      {
        enemyCount: 8,
        spawnInterval: 1.5,
        enemySpeed: 1.2,
        scorePerKill: 20,
        enemyHp: 4,
        goldPerKill: 20,
      },
    ],
    skyColor: { r: 0.02, g: 0.02, b: 0.05, a: 1 },
    ambientIntensity: 0.4,
  },
  {
    id: 'level2',
    name: 'Nebula Base',
    description: '4 方向からの総攻撃。岩を利用して防衛ラインを作れ。',
    difficulty: 'normal',
    mapSize: 24,
    startGold: 200,
    startLives: 20,
    spawnPoints: [
      { x: 11, z: 11 },
      { x: -11, z: 11 },
      { x: 11, z: -11 },
      { x: -11, z: -11 },
    ],
    basePosition: { x: 0, z: 0 },
    obstacles: [
      { x: 3, z: 3, type: 'rock' },
      { x: -3, z: 3, type: 'rock' },
      { x: 3, z: -3, type: 'rock' },
      { x: -3, z: -3, type: 'rock' },
      { x: 5, z: 0, type: 'wall' },
      { x: -5, z: 0, type: 'wall' },
    ],
    waves: [
      {
        enemyCount: 5,
        spawnInterval: 2.0,
        enemySpeed: 1.0,
        scorePerKill: 15,
        enemyHp: 4,
        goldPerKill: 15,
      },
      {
        enemyCount: 8,
        spawnInterval: 1.5,
        enemySpeed: 1.3,
        scorePerKill: 20,
        enemyHp: 6,
        goldPerKill: 20,
      },
      {
        enemyCount: 12,
        spawnInterval: 1.0,
        enemySpeed: 1.5,
        scorePerKill: 25,
        enemyHp: 8,
        goldPerKill: 25,
      },
      {
        enemyCount: 15,
        spawnInterval: 0.8,
        enemySpeed: 1.8,
        scorePerKill: 30,
        enemyHp: 10,
        goldPerKill: 30,
      },
    ],
    skyColor: { r: 0.02, g: 0.01, b: 0.08, a: 1 },
    ambientIntensity: 0.3,
  },
  {
    id: 'level3',
    name: 'Dark Matter Core',
    description: '最終決戦。無数の敵を食い止めろ。',
    difficulty: 'hard',
    mapSize: 28,
    startGold: 150,
    startLives: 15,
    spawnPoints: [
      { x: 13, z: 13 },
      { x: -13, z: 13 },
      { x: 13, z: -13 },
      { x: -13, z: -13 },
      { x: 0, z: 13 },
      { x: 0, z: -13 },
    ],
    basePosition: { x: 0, z: 0 },
    obstacles: [
      { x: 4, z: 0, type: 'wall' },
      { x: -4, z: 0, type: 'wall' },
      { x: 0, z: 4, type: 'wall' },
      { x: 0, z: -4, type: 'wall' },
    ],
    waves: [
      {
        enemyCount: 8,
        spawnInterval: 1.5,
        enemySpeed: 1.2,
        scorePerKill: 20,
        enemyHp: 6,
        goldPerKill: 20,
      },
      {
        enemyCount: 12,
        spawnInterval: 1.0,
        enemySpeed: 1.5,
        scorePerKill: 25,
        enemyHp: 8,
        goldPerKill: 25,
      },
      {
        enemyCount: 16,
        spawnInterval: 0.7,
        enemySpeed: 1.8,
        scorePerKill: 30,
        enemyHp: 12,
        goldPerKill: 30,
      },
      {
        enemyCount: 20,
        spawnInterval: 0.5,
        enemySpeed: 2.2,
        scorePerKill: 40,
        enemyHp: 15,
        goldPerKill: 40,
      },
      {
        enemyCount: 25,
        spawnInterval: 0.4,
        enemySpeed: 2.5,
        scorePerKill: 50,
        enemyHp: 20,
        goldPerKill: 50,
      },
    ],
    skyColor: { r: 0.05, g: 0.0, b: 0.02, a: 1 },
    ambientIntensity: 0.2,
  },
]
